<?php

/**
 * This source file is proprietary and part of Rebilly.
 *
 * (c) Rebilly SRL
 *     Rebilly Ltd.
 *     Rebilly Inc.
 *
 * @see https://www.rebilly.com
 */

declare(strict_types=1);

namespace Rebilly\Sdk\Model;

use Rebilly\Sdk\Exception\UnknownDiscriminatorValueException;

class AdjustReadyToPayoutPaymentMethodFactory
{
    public static function from(array $data = []): AdjustReadyToPayoutPaymentMethod
    {
        return match ($data['paymentMethod']) {
            'AdvCash' => AdjustReadyToPayoutGeneric::from($data),
            'Alfa-click' => AdjustReadyToPayoutGeneric::from($data),
            'Alipay' => AdjustReadyToPayoutGeneric::from($data),
            'AstroPay Card' => AdjustReadyToPayoutGeneric::from($data),
            'AstroPay-GO' => AdjustReadyToPayoutGeneric::from($data),
            'Baloto' => AdjustReadyToPayoutGeneric::from($data),
            'Bancontact' => AdjustReadyToPayoutGeneric::from($data),
            'Bancontact-mobile' => AdjustReadyToPayoutGeneric::from($data),
            'BankReferenced' => AdjustReadyToPayoutGeneric::from($data),
            'Beeline' => AdjustReadyToPayoutGeneric::from($data),
            'Belfius-direct-net' => AdjustReadyToPayoutGeneric::from($data),
            'Bizum' => AdjustReadyToPayoutGeneric::from($data),
            'Boleto' => AdjustReadyToPayoutGeneric::from($data),
            'CASHlib' => AdjustReadyToPayoutGeneric::from($data),
            'CODVoucher' => AdjustReadyToPayoutGeneric::from($data),
            'CashToCode' => AdjustReadyToPayoutGeneric::from($data),
            'China UnionPay' => AdjustReadyToPayoutGeneric::from($data),
            'Cleo' => AdjustReadyToPayoutGeneric::from($data),
            'Conekta-oxxo' => AdjustReadyToPayoutGeneric::from($data),
            'Cupon-de-pagos' => AdjustReadyToPayoutGeneric::from($data),
            'EPS' => AdjustReadyToPayoutGeneric::from($data),
            'Efecty' => AdjustReadyToPayoutGeneric::from($data),
            'FasterPay' => AdjustReadyToPayoutGeneric::from($data),
            'Flexepin' => AdjustReadyToPayoutGeneric::from($data),
            'Giropay' => AdjustReadyToPayoutGeneric::from($data),
            'Google Pay' => AdjustReadyToPayoutGeneric::from($data),
            'Gpaysafe' => AdjustReadyToPayoutGeneric::from($data),
            'ING-homepay' => AdjustReadyToPayoutGeneric::from($data),
            'INOVAPAY-pin' => AdjustReadyToPayoutGeneric::from($data),
            'INOVAPAY-wallet' => AdjustReadyToPayoutGeneric::from($data),
            'InstaDebit' => AdjustReadyToPayoutGeneric::from($data),
            'InstantPayments' => AdjustReadyToPayoutGeneric::from($data),
            'Interac' => AdjustReadyToPayoutGeneric::from($data),
            'Interac-eTransfer' => AdjustReadyToPayoutGeneric::from($data),
            'Interac-online' => AdjustReadyToPayoutGeneric::from($data),
            'Jeton' => AdjustReadyToPayoutGeneric::from($data),
            'KNOT' => AdjustReadyToPayoutGeneric::from($data),
            'Khelocard' => AdjustReadyToPayoutGeneric::from($data),
            'Klarna' => AdjustReadyToPayoutGeneric::from($data),
            'MTS' => AdjustReadyToPayoutGeneric::from($data),
            'Matrix' => AdjustReadyToPayoutGeneric::from($data),
            'MaxiCash' => AdjustReadyToPayoutGeneric::from($data),
            'Megafon' => AdjustReadyToPayoutGeneric::from($data),
            'MiFinity-eWallet' => AdjustReadyToPayoutGeneric::from($data),
            'MuchBetter' => AdjustReadyToPayoutGeneric::from($data),
            'Multibanco' => AdjustReadyToPayoutGeneric::from($data),
            'Neosurf' => AdjustReadyToPayoutGeneric::from($data),
            'Netbanking' => AdjustReadyToPayoutGeneric::from($data),
            'Neteller' => AdjustReadyToPayoutGeneric::from($data),
            'Nordea-Solo' => AdjustReadyToPayoutGeneric::from($data),
            'OXXO' => AdjustReadyToPayoutGeneric::from($data),
            'OchaPay' => AdjustReadyToPayoutGeneric::from($data),
            'Onlineueberweisen' => AdjustReadyToPayoutGeneric::from($data),
            'P24' => AdjustReadyToPayoutGeneric::from($data),
            'POLi' => AdjustReadyToPayoutGeneric::from($data),
            'Pagadito' => AdjustReadyToPayoutGeneric::from($data),
            'PagoEffectivo' => AdjustReadyToPayoutGeneric::from($data),
            'Pagsmile-deposit-express' => AdjustReadyToPayoutGeneric::from($data),
            'Pagsmile-lottery' => AdjustReadyToPayoutGeneric::from($data),
            'Pay4Fun' => AdjustReadyToPayoutGeneric::from($data),
            'PayCash' => AdjustReadyToPayoutGeneric::from($data),
            'PayTabs' => AdjustReadyToPayoutGeneric::from($data),
            'Payeer' => AdjustReadyToPayoutGeneric::from($data),
            'PaymentAsia-crypto' => AdjustReadyToPayoutGeneric::from($data),
            'Paymero' => AdjustReadyToPayoutGeneric::from($data),
            'Paynote' => AdjustReadyToPayoutGeneric::from($data),
            'Paysafecard' => AdjustReadyToPayoutGeneric::from($data),
            'Paysafecash' => AdjustReadyToPayoutGeneric::from($data),
            'Perfect-money' => AdjustReadyToPayoutGeneric::from($data),
            'PhonePe' => AdjustReadyToPayoutGeneric::from($data),
            'Piastrix' => AdjustReadyToPayoutGeneric::from($data),
            'PinPay' => AdjustReadyToPayoutGeneric::from($data),
            'PostFinance-card' => AdjustReadyToPayoutGeneric::from($data),
            'PostFinance-e-finance' => AdjustReadyToPayoutGeneric::from($data),
            'QIWI' => AdjustReadyToPayoutGeneric::from($data),
            'QPay' => AdjustReadyToPayoutGeneric::from($data),
            'QQPay' => AdjustReadyToPayoutGeneric::from($data),
            'Resurs' => AdjustReadyToPayoutGeneric::from($data),
            'SEPA' => AdjustReadyToPayoutGeneric::from($data),
            'SMSVoucher' => AdjustReadyToPayoutGeneric::from($data),
            'SafetyPay' => AdjustReadyToPayoutGeneric::from($data),
            'Skrill' => AdjustReadyToPayoutGeneric::from($data),
            'Skrill Rapid Transfer' => AdjustReadyToPayoutGeneric::from($data),
            'Sofort' => AdjustReadyToPayoutGeneric::from($data),
            'SparkPay' => AdjustReadyToPayoutGeneric::from($data),
            'Tele2' => AdjustReadyToPayoutGeneric::from($data),
            'Terminaly-RF' => AdjustReadyToPayoutGeneric::from($data),
            'ToditoCash-card' => AdjustReadyToPayoutGeneric::from($data),
            'Trustly' => AdjustReadyToPayoutGeneric::from($data),
            'UPI' => AdjustReadyToPayoutGeneric::from($data),
            'UPayCard' => AdjustReadyToPayoutGeneric::from($data),
            'USD-coin' => AdjustReadyToPayoutGeneric::from($data),
            'VCreditos' => AdjustReadyToPayoutGeneric::from($data),
            'VenusPoint' => AdjustReadyToPayoutGeneric::from($data),
            'WeChat Pay' => AdjustReadyToPayoutGeneric::from($data),
            'Webmoney' => AdjustReadyToPayoutGeneric::from($data),
            'Webpay' => AdjustReadyToPayoutGeneric::from($data),
            'Webpay Card' => AdjustReadyToPayoutGeneric::from($data),
            'Webpay-2' => AdjustReadyToPayoutGeneric::from($data),
            'XPay-P2P' => AdjustReadyToPayoutGeneric::from($data),
            'XPay-QR' => AdjustReadyToPayoutGeneric::from($data),
            'Yandex-money' => AdjustReadyToPayoutGeneric::from($data),
            'Zimpler' => AdjustReadyToPayoutGeneric::from($data),
            'Zotapay' => AdjustReadyToPayoutGeneric::from($data),
            'ach' => AdjustReadyToPayoutGeneric::from($data),
            'bank-transfer' => AdjustReadyToPayoutGeneric::from($data),
            'bank-transfer-2' => AdjustReadyToPayoutGeneric::from($data),
            'bank-transfer-3' => AdjustReadyToPayoutGeneric::from($data),
            'bank-transfer-4' => AdjustReadyToPayoutGeneric::from($data),
            'bank-transfer-5' => AdjustReadyToPayoutGeneric::from($data),
            'bank-transfer-6' => AdjustReadyToPayoutGeneric::from($data),
            'bank-transfer-7' => AdjustReadyToPayoutGeneric::from($data),
            'bank-transfer-8' => AdjustReadyToPayoutGeneric::from($data),
            'bank-transfer-9' => AdjustReadyToPayoutGeneric::from($data),
            'bitcoin' => AdjustReadyToPayoutGeneric::from($data),
            'cash' => AdjustReadyToPayoutGeneric::from($data),
            'cash-deposit' => AdjustReadyToPayoutGeneric::from($data),
            'check' => AdjustReadyToPayoutGeneric::from($data),
            'cryptocurrency' => AdjustReadyToPayoutGeneric::from($data),
            'domestic-cards' => AdjustReadyToPayoutGeneric::from($data),
            'ePay.bg' => AdjustReadyToPayoutGeneric::from($data),
            'eZeeWallet' => AdjustReadyToPayoutGeneric::from($data),
            'echeck' => AdjustReadyToPayoutGeneric::from($data),
            'ecoPayz' => AdjustReadyToPayoutGeneric::from($data),
            'ecoVoucher' => AdjustReadyToPayoutGeneric::from($data),
            'iDEAL' => AdjustReadyToPayoutGeneric::from($data),
            'iDebit' => AdjustReadyToPayoutGeneric::from($data),
            'iWallet' => AdjustReadyToPayoutGeneric::from($data),
            'instant-bank-transfer' => AdjustReadyToPayoutGeneric::from($data),
            'invoice' => AdjustReadyToPayoutGeneric::from($data),
            'jpay' => AdjustReadyToPayoutGeneric::from($data),
            'loonie' => AdjustReadyToPayoutGeneric::from($data),
            'miscellaneous' => AdjustReadyToPayoutGeneric::from($data),
            'online-bank-transfer' => AdjustReadyToPayoutGeneric::from($data),
            'oriental-wallet' => AdjustReadyToPayoutGeneric::from($data),
            'payment-card' => AdjustReadyToPayoutGeneric::from($data),
            'paypal' => AdjustReadyToPayoutGeneric::from($data),
            'phone' => AdjustReadyToPayoutGeneric::from($data),
            'plaid-account' => AdjustReadyToPayoutGeneric::from($data),
            'rapyd-checkout' => AdjustReadyToPayoutGeneric::from($data),
            'swift-dbt' => AdjustReadyToPayoutGeneric::from($data),
            'voucher' => AdjustReadyToPayoutGeneric::from($data),
            'voucher-2' => AdjustReadyToPayoutGeneric::from($data),
            'voucher-3' => AdjustReadyToPayoutGeneric::from($data),
            'voucher-4' => AdjustReadyToPayoutGeneric::from($data),
            default => throw new UnknownDiscriminatorValueException(),
        };
    }
}
