<?php

/**
 * This source file is proprietary and part of Rebilly.
 *
 * (c) Rebilly SRL
 *     Rebilly Ltd.
 *     Rebilly Inc.
 *
 * @see https://www.rebilly.com
 */

declare(strict_types=1);

namespace Rebilly\Sdk\Model;

use Rebilly\Sdk\Exception\UnknownDiscriminatorValueException;

class AdjustPaymentMethodFactory
{
    public static function from(array $data = [], array $metadata = []): AdjustPaymentMethod
    {
        return match ($data['paymentMethod']) {
            'ach' => AdjustReadyToPayAch::from($data, $metadata),
            'AdvCash' => AdjustReadyToPayGeneric::from($data, $metadata),
            'Alfa-click' => AdjustReadyToPayGeneric::from($data, $metadata),
            'Alipay' => AdjustReadyToPayGeneric::from($data, $metadata),
            'AstroPay Card' => AdjustReadyToPayGeneric::from($data, $metadata),
            'AstroPay-GO' => AdjustReadyToPayGeneric::from($data, $metadata),
            'Baloto' => AdjustReadyToPayGeneric::from($data, $metadata),
            'Bancontact' => AdjustReadyToPayGeneric::from($data, $metadata),
            'Bancontact-mobile' => AdjustReadyToPayGeneric::from($data, $metadata),
            'BankReferenced' => AdjustReadyToPayGeneric::from($data, $metadata),
            'Beeline' => AdjustReadyToPayGeneric::from($data, $metadata),
            'Belfius-direct-net' => AdjustReadyToPayGeneric::from($data, $metadata),
            'Bizum' => AdjustReadyToPayGeneric::from($data, $metadata),
            'Boleto' => AdjustReadyToPayGeneric::from($data, $metadata),
            'CASHlib' => AdjustReadyToPayGeneric::from($data, $metadata),
            'CODVoucher' => AdjustReadyToPayGeneric::from($data, $metadata),
            'CashToCode' => AdjustReadyToPayGeneric::from($data, $metadata),
            'China UnionPay' => AdjustReadyToPayGeneric::from($data, $metadata),
            'Cleo' => AdjustReadyToPayGeneric::from($data, $metadata),
            'Conekta-oxxo' => AdjustReadyToPayGeneric::from($data, $metadata),
            'Cupon-de-pagos' => AdjustReadyToPayGeneric::from($data, $metadata),
            'EPS' => AdjustReadyToPayGeneric::from($data, $metadata),
            'Efecty' => AdjustReadyToPayGeneric::from($data, $metadata),
            'FasterPay' => AdjustReadyToPayGeneric::from($data, $metadata),
            'Flexepin' => AdjustReadyToPayGeneric::from($data, $metadata),
            'Giropay' => AdjustReadyToPayGeneric::from($data, $metadata),
            'Google Pay' => AdjustReadyToPayGeneric::from($data, $metadata),
            'Gpaysafe' => AdjustReadyToPayGeneric::from($data, $metadata),
            'ING-homepay' => AdjustReadyToPayGeneric::from($data, $metadata),
            'INOVAPAY-pin' => AdjustReadyToPayGeneric::from($data, $metadata),
            'INOVAPAY-wallet' => AdjustReadyToPayGeneric::from($data, $metadata),
            'InstaDebit' => AdjustReadyToPayGeneric::from($data, $metadata),
            'InstantPayments' => AdjustReadyToPayGeneric::from($data, $metadata),
            'Interac' => AdjustReadyToPayGeneric::from($data, $metadata),
            'Interac-eTransfer' => AdjustReadyToPayGeneric::from($data, $metadata),
            'Interac-online' => AdjustReadyToPayGeneric::from($data, $metadata),
            'Jeton' => AdjustReadyToPayGeneric::from($data, $metadata),
            'KNOT' => AdjustReadyToPayGeneric::from($data, $metadata),
            'Khelocard' => AdjustReadyToPayGeneric::from($data, $metadata),
            'Klarna' => AdjustReadyToPayGeneric::from($data, $metadata),
            'MTS' => AdjustReadyToPayGeneric::from($data, $metadata),
            'Matrix' => AdjustReadyToPayGeneric::from($data, $metadata),
            'MaxiCash' => AdjustReadyToPayGeneric::from($data, $metadata),
            'Megafon' => AdjustReadyToPayGeneric::from($data, $metadata),
            'MiFinity-eWallet' => AdjustReadyToPayGeneric::from($data, $metadata),
            'MuchBetter' => AdjustReadyToPayGeneric::from($data, $metadata),
            'Multibanco' => AdjustReadyToPayGeneric::from($data, $metadata),
            'Neosurf' => AdjustReadyToPayGeneric::from($data, $metadata),
            'Netbanking' => AdjustReadyToPayGeneric::from($data, $metadata),
            'Neteller' => AdjustReadyToPayGeneric::from($data, $metadata),
            'Nordea-Solo' => AdjustReadyToPayGeneric::from($data, $metadata),
            'OXXO' => AdjustReadyToPayGeneric::from($data, $metadata),
            'OchaPay' => AdjustReadyToPayGeneric::from($data, $metadata),
            'Onlineueberweisen' => AdjustReadyToPayGeneric::from($data, $metadata),
            'P24' => AdjustReadyToPayGeneric::from($data, $metadata),
            'POLi' => AdjustReadyToPayGeneric::from($data, $metadata),
            'Pagadito' => AdjustReadyToPayGeneric::from($data, $metadata),
            'PagoEffectivo' => AdjustReadyToPayGeneric::from($data, $metadata),
            'Pagsmile-deposit-express' => AdjustReadyToPayGeneric::from($data, $metadata),
            'Pagsmile-lottery' => AdjustReadyToPayGeneric::from($data, $metadata),
            'Pay4Fun' => AdjustReadyToPayGeneric::from($data, $metadata),
            'PayCash' => AdjustReadyToPayGeneric::from($data, $metadata),
            'PayTabs' => AdjustReadyToPayGeneric::from($data, $metadata),
            'Payeer' => AdjustReadyToPayGeneric::from($data, $metadata),
            'PaymentAsia-crypto' => AdjustReadyToPayGeneric::from($data, $metadata),
            'Paymero' => AdjustReadyToPayGeneric::from($data, $metadata),
            'Paynote' => AdjustReadyToPayGeneric::from($data, $metadata),
            'Paysafecard' => AdjustReadyToPayGeneric::from($data, $metadata),
            'Paysafecash' => AdjustReadyToPayGeneric::from($data, $metadata),
            'Perfect-money' => AdjustReadyToPayGeneric::from($data, $metadata),
            'PhonePe' => AdjustReadyToPayGeneric::from($data, $metadata),
            'Piastrix' => AdjustReadyToPayGeneric::from($data, $metadata),
            'PinPay' => AdjustReadyToPayGeneric::from($data, $metadata),
            'PostFinance-card' => AdjustReadyToPayGeneric::from($data, $metadata),
            'PostFinance-e-finance' => AdjustReadyToPayGeneric::from($data, $metadata),
            'QIWI' => AdjustReadyToPayGeneric::from($data, $metadata),
            'QPay' => AdjustReadyToPayGeneric::from($data, $metadata),
            'QQPay' => AdjustReadyToPayGeneric::from($data, $metadata),
            'Resurs' => AdjustReadyToPayGeneric::from($data, $metadata),
            'SEPA' => AdjustReadyToPayGeneric::from($data, $metadata),
            'SMSVoucher' => AdjustReadyToPayGeneric::from($data, $metadata),
            'SafetyPay' => AdjustReadyToPayGeneric::from($data, $metadata),
            'Skrill' => AdjustReadyToPayGeneric::from($data, $metadata),
            'Skrill Rapid Transfer' => AdjustReadyToPayGeneric::from($data, $metadata),
            'Sofort' => AdjustReadyToPayGeneric::from($data, $metadata),
            'SparkPay' => AdjustReadyToPayGeneric::from($data, $metadata),
            'Tele2' => AdjustReadyToPayGeneric::from($data, $metadata),
            'Terminaly-RF' => AdjustReadyToPayGeneric::from($data, $metadata),
            'ToditoCash-card' => AdjustReadyToPayGeneric::from($data, $metadata),
            'Trustly' => AdjustReadyToPayGeneric::from($data, $metadata),
            'UPI' => AdjustReadyToPayGeneric::from($data, $metadata),
            'UPayCard' => AdjustReadyToPayGeneric::from($data, $metadata),
            'USD-coin' => AdjustReadyToPayGeneric::from($data, $metadata),
            'VCreditos' => AdjustReadyToPayGeneric::from($data, $metadata),
            'VenusPoint' => AdjustReadyToPayGeneric::from($data, $metadata),
            'WeChat Pay' => AdjustReadyToPayGeneric::from($data, $metadata),
            'Webmoney' => AdjustReadyToPayGeneric::from($data, $metadata),
            'Webpay' => AdjustReadyToPayGeneric::from($data, $metadata),
            'Webpay Card' => AdjustReadyToPayGeneric::from($data, $metadata),
            'Webpay-2' => AdjustReadyToPayGeneric::from($data, $metadata),
            'XPay-P2P' => AdjustReadyToPayGeneric::from($data, $metadata),
            'XPay-QR' => AdjustReadyToPayGeneric::from($data, $metadata),
            'Yandex-money' => AdjustReadyToPayGeneric::from($data, $metadata),
            'Zimpler' => AdjustReadyToPayGeneric::from($data, $metadata),
            'Zotapay' => AdjustReadyToPayGeneric::from($data, $metadata),
            'bank-transfer' => AdjustReadyToPayGeneric::from($data, $metadata),
            'bank-transfer-2' => AdjustReadyToPayGeneric::from($data, $metadata),
            'bank-transfer-3' => AdjustReadyToPayGeneric::from($data, $metadata),
            'bank-transfer-4' => AdjustReadyToPayGeneric::from($data, $metadata),
            'bank-transfer-5' => AdjustReadyToPayGeneric::from($data, $metadata),
            'bank-transfer-6' => AdjustReadyToPayGeneric::from($data, $metadata),
            'bank-transfer-7' => AdjustReadyToPayGeneric::from($data, $metadata),
            'bank-transfer-8' => AdjustReadyToPayGeneric::from($data, $metadata),
            'bank-transfer-9' => AdjustReadyToPayGeneric::from($data, $metadata),
            'bitcoin' => AdjustReadyToPayGeneric::from($data, $metadata),
            'cash' => AdjustReadyToPayGeneric::from($data, $metadata),
            'cash-deposit' => AdjustReadyToPayGeneric::from($data, $metadata),
            'check' => AdjustReadyToPayGeneric::from($data, $metadata),
            'cryptocurrency' => AdjustReadyToPayGeneric::from($data, $metadata),
            'domestic-cards' => AdjustReadyToPayGeneric::from($data, $metadata),
            'ePay.bg' => AdjustReadyToPayGeneric::from($data, $metadata),
            'eZeeWallet' => AdjustReadyToPayGeneric::from($data, $metadata),
            'echeck' => AdjustReadyToPayGeneric::from($data, $metadata),
            'ecoPayz' => AdjustReadyToPayGeneric::from($data, $metadata),
            'ecoVoucher' => AdjustReadyToPayGeneric::from($data, $metadata),
            'iDEAL' => AdjustReadyToPayGeneric::from($data, $metadata),
            'iDebit' => AdjustReadyToPayGeneric::from($data, $metadata),
            'iWallet' => AdjustReadyToPayGeneric::from($data, $metadata),
            'instant-bank-transfer' => AdjustReadyToPayGeneric::from($data, $metadata),
            'invoice' => AdjustReadyToPayGeneric::from($data, $metadata),
            'jpay' => AdjustReadyToPayGeneric::from($data, $metadata),
            'loonie' => AdjustReadyToPayGeneric::from($data, $metadata),
            'miscellaneous' => AdjustReadyToPayGeneric::from($data, $metadata),
            'online-bank-transfer' => AdjustReadyToPayGeneric::from($data, $metadata),
            'oriental-wallet' => AdjustReadyToPayGeneric::from($data, $metadata),
            'phone' => AdjustReadyToPayGeneric::from($data, $metadata),
            'plaid-account' => AdjustReadyToPayGeneric::from($data, $metadata),
            'rapyd-checkout' => AdjustReadyToPayGeneric::from($data, $metadata),
            'swift-dbt' => AdjustReadyToPayGeneric::from($data, $metadata),
            'voucher' => AdjustReadyToPayGeneric::from($data, $metadata),
            'voucher-2' => AdjustReadyToPayGeneric::from($data, $metadata),
            'voucher-3' => AdjustReadyToPayGeneric::from($data, $metadata),
            'voucher-4' => AdjustReadyToPayGeneric::from($data, $metadata),
            'payment-card' => AdjustReadyToPayPaymentCard::from($data, $metadata),
            'paypal' => AdjustReadyToPayPaypal::from($data, $metadata),
            default => throw new UnknownDiscriminatorValueException(),
        };
    }
}
