<?php

/**
 * This source file is proprietary and part of Rebilly.
 *
 * (c) Rebilly SRL
 *     Rebilly Ltd.
 *     Rebilly Inc.
 *
 * @see https://www.rebilly.com
 */

declare(strict_types=1);

namespace Rebilly\Sdk\Model;

use Rebilly\Sdk\Exception\UnknownDiscriminatorValueException;

class CustomerDefaultPaymentInstrumentFactory
{
    public static function from(array $data = [], array $metadata = []): CustomerDefaultPaymentInstrument
    {
        if (isset($data['paymentInstrumentId'])) {
            return VaultedInstrument::from($data, $metadata);
        }

        return match ($data['method']) {
            'AdvCash' => AlternativePaymentInstrument::from($data, $metadata),
            'Aera' => AlternativePaymentInstrument::from($data, $metadata),
            'Affirm' => AlternativePaymentInstrument::from($data, $metadata),
            'Afterpay' => AlternativePaymentInstrument::from($data, $metadata),
            'Aircash' => AlternativePaymentInstrument::from($data, $metadata),
            'Airpay' => AlternativePaymentInstrument::from($data, $metadata),
            'Alfa-click' => AlternativePaymentInstrument::from($data, $metadata),
            'Alipay' => AlternativePaymentInstrument::from($data, $metadata),
            'AmazonPay' => AlternativePaymentInstrument::from($data, $metadata),
            'Apple Pay' => AlternativePaymentInstrument::from($data, $metadata),
            'AstroPay Card' => AlternativePaymentInstrument::from($data, $metadata),
            'AstroPay-GO' => AlternativePaymentInstrument::from($data, $metadata),
            'Baloto' => AlternativePaymentInstrument::from($data, $metadata),
            'Bancontact' => AlternativePaymentInstrument::from($data, $metadata),
            'Bancontact-mobile' => AlternativePaymentInstrument::from($data, $metadata),
            'BankReferenced' => AlternativePaymentInstrument::from($data, $metadata),
            'BankSEND' => AlternativePaymentInstrument::from($data, $metadata),
            'Beeline' => AlternativePaymentInstrument::from($data, $metadata),
            'Belfius-direct-net' => AlternativePaymentInstrument::from($data, $metadata),
            'Bizum' => AlternativePaymentInstrument::from($data, $metadata),
            'Blik' => AlternativePaymentInstrument::from($data, $metadata),
            'Boleto' => AlternativePaymentInstrument::from($data, $metadata),
            'Boleto-2' => AlternativePaymentInstrument::from($data, $metadata),
            'Boleto-3' => AlternativePaymentInstrument::from($data, $metadata),
            'CASHlib' => AlternativePaymentInstrument::from($data, $metadata),
            'CCAvenue' => AlternativePaymentInstrument::from($data, $metadata),
            'CODVoucher' => AlternativePaymentInstrument::from($data, $metadata),
            'CashToCode' => AlternativePaymentInstrument::from($data, $metadata),
            'China UnionPay' => AlternativePaymentInstrument::from($data, $metadata),
            'Clearpay' => AlternativePaymentInstrument::from($data, $metadata),
            'Cleo' => AlternativePaymentInstrument::from($data, $metadata),
            'Conekta-oxxo' => AlternativePaymentInstrument::from($data, $metadata),
            'Conekta-spei' => AlternativePaymentInstrument::from($data, $metadata),
            'Cupon-de-pagos' => AlternativePaymentInstrument::from($data, $metadata),
            'CyberSource' => AlternativePaymentInstrument::from($data, $metadata),
            'Dimoco-pay-smart' => AlternativePaymentInstrument::from($data, $metadata),
            'Directa24Card' => AlternativePaymentInstrument::from($data, $metadata),
            'EPS' => AlternativePaymentInstrument::from($data, $metadata),
            'Efecty' => AlternativePaymentInstrument::from($data, $metadata),
            'Ethereum' => AlternativePaymentInstrument::from($data, $metadata),
            'FasterPay' => AlternativePaymentInstrument::from($data, $metadata),
            'Flexepin' => AlternativePaymentInstrument::from($data, $metadata),
            'Giropay' => AlternativePaymentInstrument::from($data, $metadata),
            'Google Pay' => AlternativePaymentInstrument::from($data, $metadata),
            'Gpaysafe' => AlternativePaymentInstrument::from($data, $metadata),
            'ING-homepay' => AlternativePaymentInstrument::from($data, $metadata),
            'INOVAPAY-pin' => AlternativePaymentInstrument::from($data, $metadata),
            'INOVAPAY-wallet' => AlternativePaymentInstrument::from($data, $metadata),
            'InstaDebit' => AlternativePaymentInstrument::from($data, $metadata),
            'InstantPayments' => AlternativePaymentInstrument::from($data, $metadata),
            'Interac' => AlternativePaymentInstrument::from($data, $metadata),
            'Interac-eTransfer' => AlternativePaymentInstrument::from($data, $metadata),
            'Interac-express-connect' => AlternativePaymentInstrument::from($data, $metadata),
            'Interac-online' => AlternativePaymentInstrument::from($data, $metadata),
            'Jeton' => AlternativePaymentInstrument::from($data, $metadata),
            'JetonCash' => AlternativePaymentInstrument::from($data, $metadata),
            'KNOT' => AlternativePaymentInstrument::from($data, $metadata),
            'KakaoPay' => AlternativePaymentInstrument::from($data, $metadata),
            'Khelocard' => AlternativePaymentInstrument::from($data, $metadata),
            'Klarna' => AlternativePaymentInstrument::from($data, $metadata),
            'LPG-online' => AlternativePaymentInstrument::from($data, $metadata),
            'LPG-payment-card' => AlternativePaymentInstrument::from($data, $metadata),
            'Litecoin' => AlternativePaymentInstrument::from($data, $metadata),
            'MTS' => AlternativePaymentInstrument::from($data, $metadata),
            'Matrix' => AlternativePaymentInstrument::from($data, $metadata),
            'MaxiCash' => AlternativePaymentInstrument::from($data, $metadata),
            'Megafon' => AlternativePaymentInstrument::from($data, $metadata),
            'MercadoPago' => AlternativePaymentInstrument::from($data, $metadata),
            'MiFinity-eWallet' => AlternativePaymentInstrument::from($data, $metadata),
            'MobilePay' => AlternativePaymentInstrument::from($data, $metadata),
            'Mollie' => AlternativePaymentInstrument::from($data, $metadata),
            'MuchBetter' => AlternativePaymentInstrument::from($data, $metadata),
            'MuchBetterVoucher' => AlternativePaymentInstrument::from($data, $metadata),
            'Multibanco' => AlternativePaymentInstrument::from($data, $metadata),
            'MyFatoorah' => AlternativePaymentInstrument::from($data, $metadata),
            'Neosurf' => AlternativePaymentInstrument::from($data, $metadata),
            'Netbanking' => AlternativePaymentInstrument::from($data, $metadata),
            'Neteller' => AlternativePaymentInstrument::from($data, $metadata),
            'Nordea-Solo' => AlternativePaymentInstrument::from($data, $metadata),
            'NordikCoin' => AlternativePaymentInstrument::from($data, $metadata),
            'OXXO' => AlternativePaymentInstrument::from($data, $metadata),
            'OchaPay' => AlternativePaymentInstrument::from($data, $metadata),
            'Onlineueberweisen' => AlternativePaymentInstrument::from($data, $metadata),
            'P24' => AlternativePaymentInstrument::from($data, $metadata),
            'PIX' => AlternativePaymentInstrument::from($data, $metadata),
            'POLi' => AlternativePaymentInstrument::from($data, $metadata),
            'Pagadito' => AlternativePaymentInstrument::from($data, $metadata),
            'PagoEffectivo' => AlternativePaymentInstrument::from($data, $metadata),
            'Pagsmile-deposit-express' => AlternativePaymentInstrument::from($data, $metadata),
            'Pagsmile-lottery' => AlternativePaymentInstrument::from($data, $metadata),
            'Pay4Fun' => AlternativePaymentInstrument::from($data, $metadata),
            'PayCash' => AlternativePaymentInstrument::from($data, $metadata),
            'PayTabs' => AlternativePaymentInstrument::from($data, $metadata),
            'PayU' => AlternativePaymentInstrument::from($data, $metadata),
            'PayULatam' => AlternativePaymentInstrument::from($data, $metadata),
            'Payco' => AlternativePaymentInstrument::from($data, $metadata),
            'Payeer' => AlternativePaymentInstrument::from($data, $metadata),
            'PaymentAsia-crypto' => AlternativePaymentInstrument::from($data, $metadata),
            'Paymero' => AlternativePaymentInstrument::from($data, $metadata),
            'Paymero-QR' => AlternativePaymentInstrument::from($data, $metadata),
            'Paynote' => AlternativePaymentInstrument::from($data, $metadata),
            'Paysafecard' => AlternativePaymentInstrument::from($data, $metadata),
            'Perfect-money' => AlternativePaymentInstrument::from($data, $metadata),
            'PhonePe' => AlternativePaymentInstrument::from($data, $metadata),
            'Piastrix' => AlternativePaymentInstrument::from($data, $metadata),
            'PinPay' => AlternativePaymentInstrument::from($data, $metadata),
            'PostFinance-card' => AlternativePaymentInstrument::from($data, $metadata),
            'PostFinance-e-finance' => AlternativePaymentInstrument::from($data, $metadata),
            'QIWI' => AlternativePaymentInstrument::from($data, $metadata),
            'QPay' => AlternativePaymentInstrument::from($data, $metadata),
            'QQPay' => AlternativePaymentInstrument::from($data, $metadata),
            'Quickpay' => AlternativePaymentInstrument::from($data, $metadata),
            'Resurs' => AlternativePaymentInstrument::from($data, $metadata),
            'Ripple' => AlternativePaymentInstrument::from($data, $metadata),
            'SEPA' => AlternativePaymentInstrument::from($data, $metadata),
            'SMSVoucher' => AlternativePaymentInstrument::from($data, $metadata),
            'SPEI' => AlternativePaymentInstrument::from($data, $metadata),
            'SafetyPay' => AlternativePaymentInstrument::from($data, $metadata),
            'Samsung Pay' => AlternativePaymentInstrument::from($data, $metadata),
            'Siirto' => AlternativePaymentInstrument::from($data, $metadata),
            'Skrill' => AlternativePaymentInstrument::from($data, $metadata),
            'Skrill Rapid Transfer' => AlternativePaymentInstrument::from($data, $metadata),
            'Sofort' => AlternativePaymentInstrument::from($data, $metadata),
            'SparkPay' => AlternativePaymentInstrument::from($data, $metadata),
            'TWINT' => AlternativePaymentInstrument::from($data, $metadata),
            'Tele2' => AlternativePaymentInstrument::from($data, $metadata),
            'Telr' => AlternativePaymentInstrument::from($data, $metadata),
            'Terminaly-RF' => AlternativePaymentInstrument::from($data, $metadata),
            'Tether' => AlternativePaymentInstrument::from($data, $metadata),
            'ToditoCash-card' => AlternativePaymentInstrument::from($data, $metadata),
            'Trustly' => AlternativePaymentInstrument::from($data, $metadata),
            'Tupay' => AlternativePaymentInstrument::from($data, $metadata),
            'UPI' => AlternativePaymentInstrument::from($data, $metadata),
            'UPayCard' => AlternativePaymentInstrument::from($data, $metadata),
            'USD-coin' => AlternativePaymentInstrument::from($data, $metadata),
            'UniCrypt' => AlternativePaymentInstrument::from($data, $metadata),
            'VCreditos' => AlternativePaymentInstrument::from($data, $metadata),
            'VegaWallet' => AlternativePaymentInstrument::from($data, $metadata),
            'VenusPoint' => AlternativePaymentInstrument::from($data, $metadata),
            'Viva' => AlternativePaymentInstrument::from($data, $metadata),
            'Wallet88' => AlternativePaymentInstrument::from($data, $metadata),
            'WeChat Pay' => AlternativePaymentInstrument::from($data, $metadata),
            'Webmoney' => AlternativePaymentInstrument::from($data, $metadata),
            'Webpay' => AlternativePaymentInstrument::from($data, $metadata),
            'Webpay Card' => AlternativePaymentInstrument::from($data, $metadata),
            'Webpay-2' => AlternativePaymentInstrument::from($data, $metadata),
            'XPay-P2P' => AlternativePaymentInstrument::from($data, $metadata),
            'XPay-QR' => AlternativePaymentInstrument::from($data, $metadata),
            'Yandex-money' => AlternativePaymentInstrument::from($data, $metadata),
            'Zimpler' => AlternativePaymentInstrument::from($data, $metadata),
            'Zip' => AlternativePaymentInstrument::from($data, $metadata),
            'Zotapay' => AlternativePaymentInstrument::from($data, $metadata),
            'bank-transfer' => AlternativePaymentInstrument::from($data, $metadata),
            'bank-transfer-2' => AlternativePaymentInstrument::from($data, $metadata),
            'bank-transfer-3' => AlternativePaymentInstrument::from($data, $metadata),
            'bank-transfer-4' => AlternativePaymentInstrument::from($data, $metadata),
            'bank-transfer-5' => AlternativePaymentInstrument::from($data, $metadata),
            'bank-transfer-6' => AlternativePaymentInstrument::from($data, $metadata),
            'bank-transfer-7' => AlternativePaymentInstrument::from($data, $metadata),
            'bank-transfer-8' => AlternativePaymentInstrument::from($data, $metadata),
            'bank-transfer-9' => AlternativePaymentInstrument::from($data, $metadata),
            'bitcoin' => AlternativePaymentInstrument::from($data, $metadata),
            'cash-deposit' => AlternativePaymentInstrument::from($data, $metadata),
            'cryptocurrency' => AlternativePaymentInstrument::from($data, $metadata),
            'domestic-cards' => AlternativePaymentInstrument::from($data, $metadata),
            'e-wallet' => AlternativePaymentInstrument::from($data, $metadata),
            'ePay.bg' => AlternativePaymentInstrument::from($data, $metadata),
            'eZeeWallet' => AlternativePaymentInstrument::from($data, $metadata),
            'echeck' => AlternativePaymentInstrument::from($data, $metadata),
            'ecoPayz' => AlternativePaymentInstrument::from($data, $metadata),
            'ecoPayzTurkey' => AlternativePaymentInstrument::from($data, $metadata),
            'ecoVoucher' => AlternativePaymentInstrument::from($data, $metadata),
            'ezyEFT' => AlternativePaymentInstrument::from($data, $metadata),
            'iCashOne Voucher' => AlternativePaymentInstrument::from($data, $metadata),
            'iDEAL' => AlternativePaymentInstrument::from($data, $metadata),
            'iDebit' => AlternativePaymentInstrument::from($data, $metadata),
            'iWallet' => AlternativePaymentInstrument::from($data, $metadata),
            'instant-bank-transfer' => AlternativePaymentInstrument::from($data, $metadata),
            'invoice' => AlternativePaymentInstrument::from($data, $metadata),
            'jpay' => AlternativePaymentInstrument::from($data, $metadata),
            'loonie' => AlternativePaymentInstrument::from($data, $metadata),
            'miscellaneous' => AlternativePaymentInstrument::from($data, $metadata),
            'online-bank-transfer' => AlternativePaymentInstrument::from($data, $metadata),
            'oriental-wallet' => AlternativePaymentInstrument::from($data, $metadata),
            'phone' => AlternativePaymentInstrument::from($data, $metadata),
            'rapyd-checkout' => AlternativePaymentInstrument::from($data, $metadata),
            'rebilly-hosted-payment-form' => AlternativePaymentInstrument::from($data, $metadata),
            'reverse-withdrawal' => AlternativePaymentInstrument::from($data, $metadata),
            'swift-dbt' => AlternativePaymentInstrument::from($data, $metadata),
            'voucher' => AlternativePaymentInstrument::from($data, $metadata),
            'voucher-2' => AlternativePaymentInstrument::from($data, $metadata),
            'voucher-3' => AlternativePaymentInstrument::from($data, $metadata),
            'voucher-4' => AlternativePaymentInstrument::from($data, $metadata),
            'cash' => CashInstrument::from($data, $metadata),
            'check' => CheckInstrument::from($data, $metadata),
            default => throw new UnknownDiscriminatorValueException(),
        };
    }
}
