<?php
/**
 * This source file is proprietary and part of Rebilly.
 *
 * (c) Rebilly SRL
 *     Rebilly Ltd.
 *     Rebilly Inc.
 *
 * @see https://www.rebilly.com
 */

declare(strict_types=1);

namespace Rebilly\Sdk\Model;

use Rebilly\Sdk\Exception\UnknownDiscriminatorValueException;

class PostPaymentInstrumentRequestFactory
{
    public static function from(array $data = []): PostPaymentInstrumentRequest
    {
        if (isset($data['token'])) {
            return new PaymentInstrumentCreateToken($data);
        }

        return match ($data['method']) {
            'AdvCash' => AlternativeInstrument::from($data),
            'Aircash' => AlternativeInstrument::from($data),
            'Alfa-click' => AlternativeInstrument::from($data),
            'Alipay' => AlternativeInstrument::from($data),
            'AstroPay Card' => AlternativeInstrument::from($data),
            'AstroPay-GO' => AlternativeInstrument::from($data),
            'Baloto' => AlternativeInstrument::from($data),
            'Bancontact' => AlternativeInstrument::from($data),
            'Bancontact-mobile' => AlternativeInstrument::from($data),
            'BankReferenced' => AlternativeInstrument::from($data),
            'Beeline' => AlternativeInstrument::from($data),
            'Belfius-direct-net' => AlternativeInstrument::from($data),
            'Bizum' => AlternativeInstrument::from($data),
            'Boleto' => AlternativeInstrument::from($data),
            'CASHlib' => AlternativeInstrument::from($data),
            'CODVoucher' => AlternativeInstrument::from($data),
            'CashToCode' => AlternativeInstrument::from($data),
            'China UnionPay' => AlternativeInstrument::from($data),
            'Cleo' => AlternativeInstrument::from($data),
            'Conekta-oxxo' => AlternativeInstrument::from($data),
            'Cupon-de-pagos' => AlternativeInstrument::from($data),
            'Directa24Card' => AlternativeInstrument::from($data),
            'EPS' => AlternativeInstrument::from($data),
            'Efecty' => AlternativeInstrument::from($data),
            'FasterPay' => AlternativeInstrument::from($data),
            'Flexepin' => AlternativeInstrument::from($data),
            'Giropay' => AlternativeInstrument::from($data),
            'Google Pay' => AlternativeInstrument::from($data),
            'Gpaysafe' => AlternativeInstrument::from($data),
            'ING-homepay' => AlternativeInstrument::from($data),
            'INOVAPAY-pin' => AlternativeInstrument::from($data),
            'INOVAPAY-wallet' => AlternativeInstrument::from($data),
            'InstaDebit' => AlternativeInstrument::from($data),
            'InstantPayments' => AlternativeInstrument::from($data),
            'Interac' => AlternativeInstrument::from($data),
            'Interac-eTransfer' => AlternativeInstrument::from($data),
            'Interac-online' => AlternativeInstrument::from($data),
            'Jeton' => AlternativeInstrument::from($data),
            'KNOT' => AlternativeInstrument::from($data),
            'KakaoPay' => AlternativeInstrument::from($data),
            'Klarna' => AlternativeInstrument::from($data),
            'MTS' => AlternativeInstrument::from($data),
            'Matrix' => AlternativeInstrument::from($data),
            'MaxiCash' => AlternativeInstrument::from($data),
            'Megafon' => AlternativeInstrument::from($data),
            'MercadoPago' => AlternativeInstrument::from($data),
            'MiFinity-eWallet' => AlternativeInstrument::from($data),
            'MobilePay' => AlternativeInstrument::from($data),
            'MuchBetter' => AlternativeInstrument::from($data),
            'Multibanco' => AlternativeInstrument::from($data),
            'Neosurf' => AlternativeInstrument::from($data),
            'Netbanking' => AlternativeInstrument::from($data),
            'Neteller' => AlternativeInstrument::from($data),
            'Nordea-Solo' => AlternativeInstrument::from($data),
            'OXXO' => AlternativeInstrument::from($data),
            'OchaPay' => AlternativeInstrument::from($data),
            'Onlineueberweisen' => AlternativeInstrument::from($data),
            'P24' => AlternativeInstrument::from($data),
            'PIX' => AlternativeInstrument::from($data),
            'POLi' => AlternativeInstrument::from($data),
            'Pagadito' => AlternativeInstrument::from($data),
            'PagoEffectivo' => AlternativeInstrument::from($data),
            'Pagsmile-deposit-express' => AlternativeInstrument::from($data),
            'Pagsmile-lottery' => AlternativeInstrument::from($data),
            'Pay4Fun' => AlternativeInstrument::from($data),
            'PayCash' => AlternativeInstrument::from($data),
            'PayTabs' => AlternativeInstrument::from($data),
            'Payco' => AlternativeInstrument::from($data),
            'Payeer' => AlternativeInstrument::from($data),
            'PaymentAsia-crypto' => AlternativeInstrument::from($data),
            'Paymero' => AlternativeInstrument::from($data),
            'Paynote' => AlternativeInstrument::from($data),
            'Paysafecard' => AlternativeInstrument::from($data),
            'Paysafecash' => AlternativeInstrument::from($data),
            'Perfect-money' => AlternativeInstrument::from($data),
            'PhonePe' => AlternativeInstrument::from($data),
            'Piastrix' => AlternativeInstrument::from($data),
            'PinPay' => AlternativeInstrument::from($data),
            'PostFinance-card' => AlternativeInstrument::from($data),
            'PostFinance-e-finance' => AlternativeInstrument::from($data),
            'QIWI' => AlternativeInstrument::from($data),
            'QPay' => AlternativeInstrument::from($data),
            'QQPay' => AlternativeInstrument::from($data),
            'Resurs' => AlternativeInstrument::from($data),
            'SEPA' => AlternativeInstrument::from($data),
            'SMSVoucher' => AlternativeInstrument::from($data),
            'SafetyPay' => AlternativeInstrument::from($data),
            'Samsung Pay' => AlternativeInstrument::from($data),
            'Skrill' => AlternativeInstrument::from($data),
            'Skrill Rapid Transfer' => AlternativeInstrument::from($data),
            'Sofort' => AlternativeInstrument::from($data),
            'SparkPay' => AlternativeInstrument::from($data),
            'Tele2' => AlternativeInstrument::from($data),
            'Terminaly-RF' => AlternativeInstrument::from($data),
            'ToditoCash-card' => AlternativeInstrument::from($data),
            'Trustly' => AlternativeInstrument::from($data),
            'Tupay' => AlternativeInstrument::from($data),
            'UPI' => AlternativeInstrument::from($data),
            'UPayCard' => AlternativeInstrument::from($data),
            'USD-coin' => AlternativeInstrument::from($data),
            'VCreditos' => AlternativeInstrument::from($data),
            'VenusPoint' => AlternativeInstrument::from($data),
            'Wallet88' => AlternativeInstrument::from($data),
            'WeChat Pay' => AlternativeInstrument::from($data),
            'Webmoney' => AlternativeInstrument::from($data),
            'Webpay' => AlternativeInstrument::from($data),
            'Webpay Card' => AlternativeInstrument::from($data),
            'Webpay-2' => AlternativeInstrument::from($data),
            'XPay-P2P' => AlternativeInstrument::from($data),
            'XPay-QR' => AlternativeInstrument::from($data),
            'Yandex-money' => AlternativeInstrument::from($data),
            'Zimpler' => AlternativeInstrument::from($data),
            'Zotapay' => AlternativeInstrument::from($data),
            'bank-transfer' => AlternativeInstrument::from($data),
            'bank-transfer-2' => AlternativeInstrument::from($data),
            'bank-transfer-3' => AlternativeInstrument::from($data),
            'bank-transfer-4' => AlternativeInstrument::from($data),
            'bank-transfer-5' => AlternativeInstrument::from($data),
            'bank-transfer-6' => AlternativeInstrument::from($data),
            'bank-transfer-7' => AlternativeInstrument::from($data),
            'bank-transfer-8' => AlternativeInstrument::from($data),
            'bank-transfer-9' => AlternativeInstrument::from($data),
            'bitcoin' => AlternativeInstrument::from($data),
            'cash' => AlternativeInstrument::from($data),
            'cash-deposit' => AlternativeInstrument::from($data),
            'check' => AlternativeInstrument::from($data),
            'cryptocurrency' => AlternativeInstrument::from($data),
            'domestic-cards' => AlternativeInstrument::from($data),
            'ePay.bg' => AlternativeInstrument::from($data),
            'eZeeWallet' => AlternativeInstrument::from($data),
            'ecoPayz' => AlternativeInstrument::from($data),
            'ecoVoucher' => AlternativeInstrument::from($data),
            'iDEAL' => AlternativeInstrument::from($data),
            'iDebit' => AlternativeInstrument::from($data),
            'iWallet' => AlternativeInstrument::from($data),
            'instant-bank-transfer' => AlternativeInstrument::from($data),
            'invoice' => AlternativeInstrument::from($data),
            'jpay' => AlternativeInstrument::from($data),
            'loonie' => AlternativeInstrument::from($data),
            'miscellaneous' => AlternativeInstrument::from($data),
            'online-bank-transfer' => AlternativeInstrument::from($data),
            'oriental-wallet' => AlternativeInstrument::from($data),
            'phone' => AlternativeInstrument::from($data),
            'plaid-account' => AlternativeInstrument::from($data),
            'rapyd-checkout' => AlternativeInstrument::from($data),
            'swift-dbt' => AlternativeInstrument::from($data),
            'voucher' => AlternativeInstrument::from($data),
            'voucher-2' => AlternativeInstrument::from($data),
            'voucher-3' => AlternativeInstrument::from($data),
            'voucher-4' => AlternativeInstrument::from($data),
            'wire' => AlternativeInstrument::from($data),
            'ach' => BankAccountCreatePlain::from($data),
            'payment-card' => PaymentCardCreatePlain::from($data),
            'paypal' => PayPalAccount::from($data),
            default => throw new UnknownDiscriminatorValueException(),
        };
    }
}
