<?php

/**
 * This source file is proprietary and part of Rebilly.
 *
 * (c) Rebilly SRL
 *     Rebilly Ltd.
 *     Rebilly Inc.
 *
 * @see https://www.rebilly.com
 */

declare(strict_types=1);

namespace Rebilly\Sdk\Model;

use Rebilly\Sdk\Exception\UnknownDiscriminatorValueException;

class ReadyToPayMethodsFactory
{
    public static function from(array $data = [], array $metadata = []): ReadyToPayMethods
    {
        return match ($data['method']) {
            'ach' => ReadyToPayAchMethod::from($data, $metadata),
            'AdvCash' => ReadyToPayGenericMethod::from($data, $metadata),
            'Alfa-click' => ReadyToPayGenericMethod::from($data, $metadata),
            'Alipay' => ReadyToPayGenericMethod::from($data, $metadata),
            'AstroPay Card' => ReadyToPayGenericMethod::from($data, $metadata),
            'AstroPay-GO' => ReadyToPayGenericMethod::from($data, $metadata),
            'Baloto' => ReadyToPayGenericMethod::from($data, $metadata),
            'Bancontact' => ReadyToPayGenericMethod::from($data, $metadata),
            'Bancontact-mobile' => ReadyToPayGenericMethod::from($data, $metadata),
            'BankReferenced' => ReadyToPayGenericMethod::from($data, $metadata),
            'Beeline' => ReadyToPayGenericMethod::from($data, $metadata),
            'Belfius-direct-net' => ReadyToPayGenericMethod::from($data, $metadata),
            'Bizum' => ReadyToPayGenericMethod::from($data, $metadata),
            'Boleto' => ReadyToPayGenericMethod::from($data, $metadata),
            'CASHlib' => ReadyToPayGenericMethod::from($data, $metadata),
            'CODVoucher' => ReadyToPayGenericMethod::from($data, $metadata),
            'CashToCode' => ReadyToPayGenericMethod::from($data, $metadata),
            'China UnionPay' => ReadyToPayGenericMethod::from($data, $metadata),
            'Cleo' => ReadyToPayGenericMethod::from($data, $metadata),
            'Conekta-oxxo' => ReadyToPayGenericMethod::from($data, $metadata),
            'Cupon-de-pagos' => ReadyToPayGenericMethod::from($data, $metadata),
            'EPS' => ReadyToPayGenericMethod::from($data, $metadata),
            'Efecty' => ReadyToPayGenericMethod::from($data, $metadata),
            'FasterPay' => ReadyToPayGenericMethod::from($data, $metadata),
            'Flexepin' => ReadyToPayGenericMethod::from($data, $metadata),
            'Giropay' => ReadyToPayGenericMethod::from($data, $metadata),
            'Google Pay' => ReadyToPayGenericMethod::from($data, $metadata),
            'Gpaysafe' => ReadyToPayGenericMethod::from($data, $metadata),
            'ING-homepay' => ReadyToPayGenericMethod::from($data, $metadata),
            'INOVAPAY-pin' => ReadyToPayGenericMethod::from($data, $metadata),
            'INOVAPAY-wallet' => ReadyToPayGenericMethod::from($data, $metadata),
            'InstaDebit' => ReadyToPayGenericMethod::from($data, $metadata),
            'InstantPayments' => ReadyToPayGenericMethod::from($data, $metadata),
            'Interac' => ReadyToPayGenericMethod::from($data, $metadata),
            'Interac-eTransfer' => ReadyToPayGenericMethod::from($data, $metadata),
            'Interac-online' => ReadyToPayGenericMethod::from($data, $metadata),
            'Jeton' => ReadyToPayGenericMethod::from($data, $metadata),
            'KNOT' => ReadyToPayGenericMethod::from($data, $metadata),
            'Khelocard' => ReadyToPayGenericMethod::from($data, $metadata),
            'MTS' => ReadyToPayGenericMethod::from($data, $metadata),
            'Matrix' => ReadyToPayGenericMethod::from($data, $metadata),
            'MaxiCash' => ReadyToPayGenericMethod::from($data, $metadata),
            'Megafon' => ReadyToPayGenericMethod::from($data, $metadata),
            'MiFinity-eWallet' => ReadyToPayGenericMethod::from($data, $metadata),
            'MuchBetter' => ReadyToPayGenericMethod::from($data, $metadata),
            'Multibanco' => ReadyToPayGenericMethod::from($data, $metadata),
            'Neosurf' => ReadyToPayGenericMethod::from($data, $metadata),
            'Netbanking' => ReadyToPayGenericMethod::from($data, $metadata),
            'Neteller' => ReadyToPayGenericMethod::from($data, $metadata),
            'Nordea-Solo' => ReadyToPayGenericMethod::from($data, $metadata),
            'OXXO' => ReadyToPayGenericMethod::from($data, $metadata),
            'OchaPay' => ReadyToPayGenericMethod::from($data, $metadata),
            'Onlineueberweisen' => ReadyToPayGenericMethod::from($data, $metadata),
            'P24' => ReadyToPayGenericMethod::from($data, $metadata),
            'POLi' => ReadyToPayGenericMethod::from($data, $metadata),
            'Pagadito' => ReadyToPayGenericMethod::from($data, $metadata),
            'PagoEffectivo' => ReadyToPayGenericMethod::from($data, $metadata),
            'Pagsmile-deposit-express' => ReadyToPayGenericMethod::from($data, $metadata),
            'Pagsmile-lottery' => ReadyToPayGenericMethod::from($data, $metadata),
            'Pay4Fun' => ReadyToPayGenericMethod::from($data, $metadata),
            'PayCash' => ReadyToPayGenericMethod::from($data, $metadata),
            'PayTabs' => ReadyToPayGenericMethod::from($data, $metadata),
            'Payeer' => ReadyToPayGenericMethod::from($data, $metadata),
            'PaymentAsia-crypto' => ReadyToPayGenericMethod::from($data, $metadata),
            'Paymero' => ReadyToPayGenericMethod::from($data, $metadata),
            'Paynote' => ReadyToPayGenericMethod::from($data, $metadata),
            'Paysafecard' => ReadyToPayGenericMethod::from($data, $metadata),
            'Paysafecash' => ReadyToPayGenericMethod::from($data, $metadata),
            'Perfect-money' => ReadyToPayGenericMethod::from($data, $metadata),
            'PhonePe' => ReadyToPayGenericMethod::from($data, $metadata),
            'Piastrix' => ReadyToPayGenericMethod::from($data, $metadata),
            'PinPay' => ReadyToPayGenericMethod::from($data, $metadata),
            'PostFinance-card' => ReadyToPayGenericMethod::from($data, $metadata),
            'PostFinance-e-finance' => ReadyToPayGenericMethod::from($data, $metadata),
            'QIWI' => ReadyToPayGenericMethod::from($data, $metadata),
            'QPay' => ReadyToPayGenericMethod::from($data, $metadata),
            'QQPay' => ReadyToPayGenericMethod::from($data, $metadata),
            'Resurs' => ReadyToPayGenericMethod::from($data, $metadata),
            'SEPA' => ReadyToPayGenericMethod::from($data, $metadata),
            'SMSVoucher' => ReadyToPayGenericMethod::from($data, $metadata),
            'SafetyPay' => ReadyToPayGenericMethod::from($data, $metadata),
            'Skrill' => ReadyToPayGenericMethod::from($data, $metadata),
            'Skrill Rapid Transfer' => ReadyToPayGenericMethod::from($data, $metadata),
            'Sofort' => ReadyToPayGenericMethod::from($data, $metadata),
            'SparkPay' => ReadyToPayGenericMethod::from($data, $metadata),
            'Tele2' => ReadyToPayGenericMethod::from($data, $metadata),
            'Terminaly-RF' => ReadyToPayGenericMethod::from($data, $metadata),
            'ToditoCash-card' => ReadyToPayGenericMethod::from($data, $metadata),
            'Trustly' => ReadyToPayGenericMethod::from($data, $metadata),
            'UPI' => ReadyToPayGenericMethod::from($data, $metadata),
            'UPayCard' => ReadyToPayGenericMethod::from($data, $metadata),
            'USD-coin' => ReadyToPayGenericMethod::from($data, $metadata),
            'VCreditos' => ReadyToPayGenericMethod::from($data, $metadata),
            'VenusPoint' => ReadyToPayGenericMethod::from($data, $metadata),
            'WeChat Pay' => ReadyToPayGenericMethod::from($data, $metadata),
            'Webmoney' => ReadyToPayGenericMethod::from($data, $metadata),
            'Webpay' => ReadyToPayGenericMethod::from($data, $metadata),
            'Webpay Card' => ReadyToPayGenericMethod::from($data, $metadata),
            'Webpay-2' => ReadyToPayGenericMethod::from($data, $metadata),
            'XPay-P2P' => ReadyToPayGenericMethod::from($data, $metadata),
            'XPay-QR' => ReadyToPayGenericMethod::from($data, $metadata),
            'Yandex-money' => ReadyToPayGenericMethod::from($data, $metadata),
            'Zimpler' => ReadyToPayGenericMethod::from($data, $metadata),
            'Zotapay' => ReadyToPayGenericMethod::from($data, $metadata),
            'bank-transfer' => ReadyToPayGenericMethod::from($data, $metadata),
            'bank-transfer-2' => ReadyToPayGenericMethod::from($data, $metadata),
            'bank-transfer-3' => ReadyToPayGenericMethod::from($data, $metadata),
            'bank-transfer-4' => ReadyToPayGenericMethod::from($data, $metadata),
            'bank-transfer-5' => ReadyToPayGenericMethod::from($data, $metadata),
            'bank-transfer-6' => ReadyToPayGenericMethod::from($data, $metadata),
            'bank-transfer-7' => ReadyToPayGenericMethod::from($data, $metadata),
            'bank-transfer-8' => ReadyToPayGenericMethod::from($data, $metadata),
            'bank-transfer-9' => ReadyToPayGenericMethod::from($data, $metadata),
            'bitcoin' => ReadyToPayGenericMethod::from($data, $metadata),
            'cash' => ReadyToPayGenericMethod::from($data, $metadata),
            'cash-deposit' => ReadyToPayGenericMethod::from($data, $metadata),
            'check' => ReadyToPayGenericMethod::from($data, $metadata),
            'cryptocurrency' => ReadyToPayGenericMethod::from($data, $metadata),
            'domestic-cards' => ReadyToPayGenericMethod::from($data, $metadata),
            'ePay.bg' => ReadyToPayGenericMethod::from($data, $metadata),
            'eZeeWallet' => ReadyToPayGenericMethod::from($data, $metadata),
            'echeck' => ReadyToPayGenericMethod::from($data, $metadata),
            'ecoPayz' => ReadyToPayGenericMethod::from($data, $metadata),
            'ecoVoucher' => ReadyToPayGenericMethod::from($data, $metadata),
            'iDEAL' => ReadyToPayGenericMethod::from($data, $metadata),
            'iDebit' => ReadyToPayGenericMethod::from($data, $metadata),
            'iWallet' => ReadyToPayGenericMethod::from($data, $metadata),
            'instant-bank-transfer' => ReadyToPayGenericMethod::from($data, $metadata),
            'invoice' => ReadyToPayGenericMethod::from($data, $metadata),
            'jpay' => ReadyToPayGenericMethod::from($data, $metadata),
            'loonie' => ReadyToPayGenericMethod::from($data, $metadata),
            'miscellaneous' => ReadyToPayGenericMethod::from($data, $metadata),
            'online-bank-transfer' => ReadyToPayGenericMethod::from($data, $metadata),
            'oriental-wallet' => ReadyToPayGenericMethod::from($data, $metadata),
            'phone' => ReadyToPayGenericMethod::from($data, $metadata),
            'plaid-account' => ReadyToPayGenericMethod::from($data, $metadata),
            'rapyd-checkout' => ReadyToPayGenericMethod::from($data, $metadata),
            'swift-dbt' => ReadyToPayGenericMethod::from($data, $metadata),
            'voucher' => ReadyToPayGenericMethod::from($data, $metadata),
            'voucher-2' => ReadyToPayGenericMethod::from($data, $metadata),
            'voucher-3' => ReadyToPayGenericMethod::from($data, $metadata),
            'voucher-4' => ReadyToPayGenericMethod::from($data, $metadata),
            'Klarna' => ReadyToPayKlarnaMethod::from($data, $metadata),
            'payment-card' => ReadyToPayPaymentCardMethod::from($data, $metadata),
            'paypal' => ReadyToPayPayPalMethod::from($data, $metadata),
            default => throw new UnknownDiscriminatorValueException(),
        };
    }
}
