name: Release

on:
  push:
    branches:
      - main

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

jobs:
  release:
    name: Release
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: read
    steps:
      - id: sdk-write-token
        uses: actions/create-github-app-token@bcd2ba49218906704ab6c1aa796996da409d3eb1 # v3.2.0
        with:
          client-id: ${{ vars.REBILLY_CI_SDK_WRITE_CLIENT_ID }}
          private-key: ${{ secrets.REBILLY_CI_SDK_WRITE_APP_PRIVATE_KEY }}
          permission-contents: write
          permission-pull-requests: write

      - name: Checkout Repo
        uses: actions/checkout@v4
        with:
          fetch-depth: 0
          token: ${{ steps.sdk-write-token.outputs.token }}

      - name: Setup Node.js
        uses: actions/setup-node@v6
        with:
          node-version: 20
          cache: "npm"
          registry-url: "https://npm.pkg.github.com/"
          scope: "@rebilly"
          cache-dependency-path: "package-lock.json"

      - name: Install Dependencies
        run: npm ci
        env:
          NODE_AUTH_TOKEN: ${{ secrets.GITHUB_TOKEN }}

      - name: Create Release Pull Request
        uses: changesets/action@v1
        with:
          commit: 'chore: 🔖 release new version'
          title: 'chore: 🔖 release new version'
          version: npm run version
        env:
          GITHUB_TOKEN: ${{ steps.sdk-write-token.outputs.token }}
